#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

console.log(c.clear);
for (var n = 1; n <= 12; n++) {
  console.log(n + c.multi("badger"));
}

/*
 * var n = 1;
 * while (n <= 12) {
   console.log(n + c.multi(badger));
   //n = n + 1;
   }
   */
